- name: Deploy Application
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Deploy built application
      copy:
        src: ../target/Ambilight-1.0.0.jar
        dest: /home/luca/Ambilight/
        owner: luca
        group: luca