name: Deploy with Ansible

on:
  push:
    branches:
      - main  # Runs when changes are pushed to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build Application
        run: |
          sudo apt-get install maven
          mvn clean
          mvn package

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ vars.SSH_USER }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "Key: $SSH_USER $SERVER_IP"
          ansible-playbook -i deploy/inventory.ini deploy/ansible.yml --extra-vars "ansible_ssh_pass=$SSH_PASSWORD ansible_host=$SERVER_IP ansible_user=$SSH_USER"